import { LocalizationManager } from './LocalizationManager';

/**
 * Add string here
 * also add translation in Locales file
 */
export const BaseLocalization = {
    welcome: LocalizationManager.getLocalizedStrings('welcome'),
    pleaseWait: LocalizationManager.getLocalizedStrings('pleaseWait'),
    howAreYou: LocalizationManager.getLocalizedStrings('howAreYou'),
    noInternetConnection: LocalizationManager.getLocalizedStrings('noInternetConnection'),
    favoriteTitle: LocalizationManager.getLocalizedStrings('favoriteTitle'),
    favoriteSubTitle: LocalizationManager.getLocalizedStrings('favoriteSubTitle'),
    settingTitle: LocalizationManager.getLocalizedStrings('settingTitle'),
    settingSubTitle: LocalizationManager.getLocalizedStrings('settingSubTitle'),
    generalTitle: LocalizationManager.getLocalizedStrings('generalTitle'),
    technicalTitle: LocalizationManager.getLocalizedStrings('technicalTitle'),
    contact: LocalizationManager.getLocalizedStrings('contact'),
    countryTitle: LocalizationManager.getLocalizedStrings('countryTitle'),
    contentTitle: LocalizationManager.getLocalizedStrings('contentTitle'),
    updateTitle: LocalizationManager.getLocalizedStrings('updateTitle'),
    selectCategory: LocalizationManager.getLocalizedStrings('selectCategory'),
    appInformation: LocalizationManager.getLocalizedStrings('appInformation'),
    version: LocalizationManager.getLocalizedStrings('version'),
    modificationDate: LocalizationManager.getLocalizedStrings('modificationDate'),
    contentUpdates: LocalizationManager.getLocalizedStrings('contentUpdates'),
    moreInfoTitle: LocalizationManager.getLocalizedStrings('moreInformation'),
    addRemoveFavorite: LocalizationManager.getLocalizedStrings('addRemoveFavorite'),
    removeLocally: LocalizationManager.getLocalizedStrings('removeLocally'),
    download: LocalizationManager.getLocalizedStrings('download'),
    fileOptions: LocalizationManager.getLocalizedStrings('fileOptions'),
    noDataText: LocalizationManager.getLocalizedStrings('noDataText'),
    noDataOnGrid: LocalizationManager.getLocalizedStrings('noDataOnGrid'),
    favTitleText: LocalizationManager.getLocalizedStrings('favTitleText'),
    favSubTitleText: LocalizationManager.getLocalizedStrings('favSubTitleText'),
    reTry: LocalizationManager.getLocalizedStrings('reTry'),
    authFailed: LocalizationManager.getLocalizedStrings('authenticationFailed'),
    cancel: LocalizationManager.getLocalizedStrings('cancel'),
    login: LocalizationManager.getLocalizedStrings('login'),
    noFavTitle: LocalizationManager.getLocalizedStrings('noFavTitle'),
    addToFav: LocalizationManager.getLocalizedStrings('addToFav'),
    okayButton: LocalizationManager.getLocalizedStrings('okayButton'),
    editTitle: LocalizationManager.getLocalizedStrings('editTitle'),
    editSubTitle: LocalizationManager.getLocalizedStrings('editSubTitle'),
    newListTitle: LocalizationManager.getLocalizedStrings('newListTitle'),
    newListSubTitle: LocalizationManager.getLocalizedStrings('newListSubTitle'),
    save: LocalizationManager.getLocalizedStrings('save'),
    lists: LocalizationManager.getLocalizedStrings('lists'),
    checkSubTitle: LocalizationManager.getLocalizedStrings('checkSubTitle'),
    submit: LocalizationManager.getLocalizedStrings('submit'),
    logout : LocalizationManager.getLocalizedStrings('logout'),
    logoutNow : LocalizationManager.getLocalizedStrings('logoutNow'),

};
